# Generated by Django 5.0.7 on 2024-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Dinner Time', max_length=100),
            preserve_default=False,
        ),
    ]
